/// Auto-generated by scripts/deploy.py
/// Do not edit manually. Source of truth: contracts/cord/config/*.toml
module cord::runtime_config {
    const MAX_SUPPLY: u64 = 30;
    const TERM2_DENOM_BASE: u64 = 38;

    public fun max_supply(): u64 {
        MAX_SUPPLY
    }

    public fun term2_denom_base(): u64 {
        TERM2_DENOM_BASE
    }

    public fun graduation_limit(): u64 {
        MAX_SUPPLY
    }
}
