[package]
name = "cord"
edition = "2024"
license = "MIT"
authors = ["Cord Team"]
published-at = "0xf552f121f910aff71562dcaa3d216ed2f498f9b2cb394c5b0f6e6af998be003c"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
cord = "0xf552f121f910aff71562dcaa3d216ed2f498f9b2cb394c5b0f6e6af998be003c"

[dev-dependencies]

[dev-addresses]

[environments]
testnet = "4c78adac"
