[package]
name = "cord"
edition = "2024"
license = "MIT"
authors = ["Cord Team"]
published-at = "0xeeeb538921079d3650f9e6cc8a7c1abdcbd6b2ffc358cb1c4ef42705bb1f407b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
cord = "0xeeeb538921079d3650f9e6cc8a7c1abdcbd6b2ffc358cb1c4ef42705bb1f407b"

[dev-dependencies]

[dev-addresses]

[environments]
testnet = "4c78adac"
